apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: tea 
  namespace: tea
spec:
  host: cafe.r31.org
  upstreams:
  - name: tea 
    service: tea-svc
    port: 80
  subroutes:
  - path: /tea 
    action:
      pass: tea