apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  host: cafe.f5demo.id
  tls:
    secret: cafe-secret
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
    sessionCookie:
       enable: true
       name: srv_id
       path: /
       expires: 1h
       domain: .r31.org
       httpOnly: false
       secure: true
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: /tea
    action:
      proxy:
        upstream: tea
  - path: /coffee
    action:
      proxy:
        upstream: coffee
        rewritePath: /beans
