apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
  namespace: default
  labels:
    app: juiceshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop
    spec:
      containers:
      - name: juiceshop
        image: tejaswaroop156/juice_shop_mod
        ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: juiceshop-service
  namespace: default
  labels:
    app: juiceshop
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: juiceshop
