apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: production
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: nginx
